#!/bin/bash

# Solicita ao usuário inserir o nome do cliente
read -p "Digite o nome do cliente: " client_name

# Adiciona um identificador único
id_unico=$(date +'%Y%m%d%H%M%S')

# Remove os espaços e substitui pelo caractere "-"
file_name="${id_unico}-$(echo "$client_name" | tr ' ' '-').md"

# Define o conteúdo do arquivo
content="---
type: client
created: $(date +"%Y-%m-%d - %H:%M:%S")
tags:
status: Em andamento, Finalizado
job_start: YYYY-MM-DD
job_deadline: YYYY-MM-DD
billling: R$
fee: %
contact: 
email:
phone:
note: 
---
--- 

## Escopo do Serviço

* X emails por semana.
* X automações
* Otimização das automações já feitas anteriormente

---
## Checklist Inicial

### Pré-projeto

- [ ] Criar contrato
- [ ] Criar sugestão de Pop-up de captura (com nova imagem e nova copy)
- [ ] Criar emails semanais
- [ ] Verificar métricas para decidir as melhorias a serem feitas

### Para o cliente fazer:

- Quem vai aprovar os emails antes do envio e como vai ser?
* Quem vai cuidar da ferramenta e da parte técnica?
* Como vão medir as vendas? (Link único, analytics, src)
* Para onde vai a resposta dos emails e quem vai responder?
* Formato do email (preferência: texto sem html ou o mínimo possível)
* Remetente: será enviado no nome de quem?

### Acesso à ferramenta de email:

- Link da ferramenta:
- Login:
- Senha:

### Pesquisa e questionários que fizeram anteriormente

### Acesso a pessoas para conversar e conhecer mais sobre o negócio

### Acesso a grupos:

- WhatsApp
- Facebook
- Telegram

### Depoimentos de Clientes


### Produtos
> Pedir acesso, se possível.

### Histórias da empresa/dono

- escreva aqui

### Tom de voz dos emails

### Ao iniciar

- [ ] Verificar se tem problemas com email/dominio (mxtoolbox.com/emailhealth)
- [ ] Verificar média de aberturas e cliques (ver na ferramenta)
- [ ] Pesquisa (Documento)
- [ ] Listar ideias de emails
- [ ] Criar pasta no Google Drive onde ficarão os arquivos.


---
## Desafios

- (adicionar os desafios)

---
## Ideias e Insights


---
## Plano de Ação


---
## Materiais Entregues
>  Inserir aqui tudo o que foi entregue no projeto. (Material / Data / Link)

---
## LOG
> Descrever tudo o que foi realizado (Dividido por dias.) Serve para documentar todo o projeto e facilitar para a criação de processos no futuro.
"

# Cria o arquivo com o conteúdo predefinido
echo "$content" > "$file_name"

# Abre o arquivo com o editor padrão
$EDITOR "$file_name"
