#!/bin/bash

# Solicita ao usuário inserir o nome da aula
read -p "Digite o nome da aula: " class_name

# Adiciona um identificador único
id_unico=$(date +'%Y%m%d%H%M%S')

# Remove os espaços e substitui pelo caractere "-"
file_name="${id_unico}-$(echo "$class_name" | tr ' ' '-').md"

# Define o conteúdo do arquivo
content="---
type: class
created: $(date +"%Y-%m-%d - %H:%M:%S")
class_number:
module_number:
module:
course:
author:
alias:
tags:
description:
---

- 
---

## Referências

1. 
"

# Cria o arquivo com o conteúdo predefinido
echo "$content" > "$file_name"

# Abre o arquivo com o editor padrão
$EDITOR "$file_name"
