#!/bin/bash

# Solicita ao usuário inserir o nome do lead
read -p "Digite o nome do lead: " lead_name

# Adiciona um identificador único
id_unico=$(date +'%Y%m%d%H%M%S')

# Remove os espaços e substitui pelo caractere "-"
file_name="${id_unico}-$(echo "$lead_name" | tr ' ' '-').md"

# Define o conteúdo do arquivo
content="---
type: lead
created: $(date +"%Y-%m-%d - %H:%M:%S")
lead_name:
site:
contact:
email:
email_plataform:
stage: Lead
business_model: Ecommerce
niche:
ticket: R$
traffic:
instagram:
ads:
popup_optin:
footer_optin:
welcome_series:
abandoned_cart:
weekly_emails:
last_contact:
service_price: R$
month_billing: R$
month_sales:
notes:
next_tasks: Investigar Lead
followup:
---

---

## Preços

* 1 a 3 mil/mês – 4 automações, otimização semanais, 1-2 campanhas por semana e ideias
* 2 a 4 mil/mês – 6-8 automações, otimização semanais, 2-4 campanhas por semana e ideias
* 3 a 5 mil/mês – 11 automações, otimização semanais, 5 campanhas por semana e ideias
* Conforme o faturamento deles aumentar, meus preços devem aumentar também (a cada 6 meses por exemplo – mas deixe isso acordado na ligação)

## O que procurar

1. Bom tráfego
2. Ticket Médio
3. Pode me pagar? (Tráfego x 2% x Ticket Médio). Margem tranquila para eles é de 2% a 3% do faturamento da empresa.
4. Captura Pop-up
5. Sequência de Boas-vindas (se inscreva na lista e analise quantos e-mails recebe e a qualidade destes e-mails)
6. Abandono de Carrinho (Simule a compra e abandone antes de finalizar)
7. Frequência e qualidade dos e-mails seguintes que receber (se receber)

---

## Imagens

### Visitas no Site:

### Seguidores:

### Anúncios:

---

## Checklist de Validação

### Pop-up de Captura


### Captura de Rodapé 


### Sequência de Boas-vindas


### Carrinho Abandonado


### Campanhas Semanais


### Layout dos E-mails

"

# Cria o arquivo com o conteúdo predefinido
echo "$content" > "$file_name"

# Abre o arquivo com o editor padrão
$EDITOR "$file_name"
