#!/bin/bash

# Solicita ao usuário inserir o nome da nota
read -p "Digite o nome da nota: " note_name

# Adiciona um identificador único
id_unico=$(date +'%Y%m%d%H%M%S')

# Coloca nome o arquivo
file_name="${id_unico} $(echo "$note_name").md"

# Define o conteúdo do arquivo
content="---
type: note
created: $(date +"%Y-%m-%d %H:%M:%S")
alias:
status: fleeting
tags:
---

- 

---

## Referências

1. 
"

# Cria o arquivo com o conteúdo predefinido
echo "$content" > "$file_name"

# Abre o arquivo com o editor padrão
$EDITOR "$file_name"
