#!/bin/bash

# Solicita ao usuário inserir o nome da nota
read -p "Digite o nome da nota: " note_name

# Adiciona um identificador único
id_unico=$(date +'%Y%m%d%H%M%S')

# Remove os espaços e substitui pelo caractere "-"
file_name="${id_unico}-$(echo "$note_name" | tr ' ' '-').md"

# Define o conteúdo do arquivo
content="---
type: fleeting
created: $(date +"%Y-%m-%d - %H:%M:%S")
alias:
tags:
---

- 
---

## Referências

1. 
"

# Cria o arquivo com o conteúdo predefinido
echo "$content" > "$file_name"

# Abre o arquivo com o editor padrão
$EDITOR "$file_name"
