#!/bin/bash

# Obter a data atual
current_date=$(date +'%Y-%m-%d')

# Perguntar pelo nome da tarefa
echo "Qual o nome da tarefa?"
read -r task_name

# Transformar o nome da tarefa em letras minúsculas e substituir espaços por hífens
filename=$(echo "$task_name" | tr '[:upper:]' '[:lower:]' | tr ' ' '-').md

# Verificar se o arquivo já existe
if [ -f "$filename" ]; then
    echo "Arquivo de tarefa já criado"
else
    # Perguntar pelo status da tarefa
    echo "Qual o status da tarefa? (opções: todo, next, done, in progress, waiting, cancelled)"
    read -r task_status

    # Perguntar pela descrição da tarefa
    echo "Qual a descrição da tarefa?"
    read -r task_description

    # Perguntar pela prioridade da tarefa
    echo "Qual a prioridade da tarefa? (opções: low, normal, medium, high)"
    read -r task_priority

    # Perguntar pela recorrência da tarefa
    echo "Qual a recorrência da tarefa?"
    read -r task_recurs

    # Perguntar pela data limite da tarefa
    echo "Qual a data limite para a tarefa?"
    read -r task_due

    # Perguntar pelo agendamento da tarefa
    echo "Está agendada para quando? (Se for para o calendário apenas)"
    read -r task_scheduled

    # Preencher o arquivo com os dados
    echo "---" > "$filename"
    echo "type: task" >> "$filename"
    echo "created: $current_date" >> "$filename"
    echo "status: $task_status" >> "$filename"
    echo "description: $task_description" >> "$filename"
    echo "priority: $task_priority" >> "$filename"
    echo "recurs: $task_recurs" >> "$filename"
    echo "due: $task_due" >> "$filename"
    echo "scheduled: $task_scheduled" >> "$filename"
    echo "start:" >> "$filename"
    echo "completion:" >> "$filename"
    echo "---" >> "$filename"
    echo "" >> "$filename"
    echo "## Anotações:" >> "$filename"

    # Imprimir a mensagem de sucesso
    echo "Arquivo $filename criado com sucesso!"
fi
